IF_KEYWORD = 'IF_KEYWORD'
ELIF_KEYWORD = 'ELIF_KEYWORD'
ELSE_KEYWORD = 'ELSE_KEYWORD'
FOR_LOOP_KEYWORD = 'FOR_LOOP_KEYWORD'
WHILE_LOOP_KEYWORD = 'WHILE_LOOP_KEYWORD'
FUNCASSIGN_KEYWORD = 'FUNCASSIGN_KEYWORD'
CLASSASSIGN_KEYWORD = 'CLASSASSIGN_KEYWORD'
RETURN_KEYWORD = 'RETURN_KEYWORD'
BREAK_KEYWORD = 'BREAK_KEYWORD'
CONTINUE_KEYWORD = 'CONTINUE_KEYWORD'
IMPORT_KEYWORD = 'IMPORT_KEYWORD'
PYIMPORT_KEYWORD = 'PYIMPORT_KEYWORD'
AS_KEYWORD = 'AS_KEYWORD'
TRY_KEYWORD = 'TRY_KEYWORD'
EXCEPT_KEYWORD = 'EXCEPT_KEYWORD'
EXEC_KEYWORD = 'EXEC_KEYWORD'
EVAL_KEYWORD = 'EVAL_KEYWORD'


keywords = {
    'if': IF_KEYWORD,
    'elif': ELIF_KEYWORD,
    'else': ELSE_KEYWORD,
    'for': FOR_LOOP_KEYWORD,
    'while': WHILE_LOOP_KEYWORD,
    'func': FUNCASSIGN_KEYWORD,
    'return': RETURN_KEYWORD,
    'break': BREAK_KEYWORD,
    'continue': CONTINUE_KEYWORD,
    'import': IMPORT_KEYWORD,
    'as': AS_KEYWORD,
    'class': CLASSASSIGN_KEYWORD,
    'try': TRY_KEYWORD,
    'except': EXCEPT_KEYWORD,
    'exec': EXEC_KEYWORD,
    'eval': EVAL_KEYWORD,
    'pyimport': PYIMPORT_KEYWORD,
}
