IF_KEYWORD = 'IF_KEYWORD'
ELIF_KEYWORD = 'ELIF_KEYWORD'
ELSE_KEYWORD = 'ELSE_KEYWORD'
FOR_LOOP_KEYWORD = 'FOR_LOOP_KEYWORD'
WHILE_LOOP_KEYWORD = 'WHILE_LOOP_KEYWORD'
FUNCASSIGN_KEYWORD = 'FUNCASSIGN_KEYWORD'
RETURN_KEYWORD = 'RETURN_KEYWORD'
BREAK_KEYWORD = 'BREAK_KEYWORD'
CONTINUE_KEYWORD = 'CONTINUE_KEYWORD'
IMPORT_KEYWORD = 'IMPORT_KEYWORD'
AS_KEYWORD = 'AS_KEYWORD'


keywords = {
    'if': IF_KEYWORD,
    'elif': ELIF_KEYWORD,
    'else': ELSE_KEYWORD,
    'for': FOR_LOOP_KEYWORD,
    'while': WHILE_LOOP_KEYWORD,
    'func': FUNCASSIGN_KEYWORD,
    'return': RETURN_KEYWORD,
    'break': BREAK_KEYWORD,
    'continue': CONTINUE_KEYWORD,
    'import': IMPORT_KEYWORD,
    'as': AS_KEYWORD,
}
